### ISSUE TITLE
ビルドに時間がかかりすぎる

### ISSUE THREAD

**Issue by plveir** [kuis-isle3sw/ocaml-docker#3]
## 概要
- ビルドに時間がかかりすぎる
- 10分ぐらい

- ただ、ビルドキャッシュが効くはずなので、ビルドのキャッシュが効く変更なら早くなるはず
- 手動でgithub_token発行して `build.sh` みたいなの回した方がよい？

**Comment by ksuenaga** [comment]
なにかできることあります？トークンの発行とかは僕がしないといけないのかな．

**Comment by plveir** [comment]
殴り書きだったのでちゃんとどうするかについてお伝えするのですが、
- 現状、10分ぐらいビルドに時間がかかるので、余計にgithub actionsの時間を使っている気がしてしょうがない
- したがって、個人で手動でやる運用も提案するので、どちらがいいか検討お願いします。
  - 10分使ってもいいから現状を維持する
  - 下の手順書をレポジトリに含め、githubActionsを削除する
## 個人でgithub container registryにデプロイする方法
- [ここ](https://docs.github.com/ja/github/authenticating-to-github/creating-a-personal-access-token)を参考に、次の3つの権限が付与されたトークンを作り、控える
  - write:packages
  - read:packages
  - delete:packages 
  - repoの権限も付与されてしまいますが、仕様です。不必要に大きい権限ではあるので、適宜revokeしてください
- そのトークンを{{GITHUB_TOKEN}}として、以下のコマンドを/ocaml-docker/上で叩く
```
echo {{GITHUB_TOKEN}} | docker login ghcr.io -u {{your github id}} --password-stdin
# > login succeed的なメッセージが出るはず
docker build -t ghcr.io/kuis-isle3sw/ocaml-docker:{{日付}} .
docker push ghcr.io/kuis-isle3sw/ocaml-docker:{{日付}}
```

**Comment by ksuenaga** [comment]
@plveir  これ今見たのですが，あまり実はよくわかっていません．（すみません．）僕らが container registry にアップロードしたイメージを履修者に使ってもらうのは現状では難しそうということですか？

**Comment by plveir** [comment]
@ksuenaga 説明不足でごめんなさい。履修者に使ってもらうことは十分可能です。
上で言っている問題は、AdminやTAがContainer Registryにアップロードするときの方法が微妙という話でした。
方法は二つあって、
- GithubActionsを10分使って(!!)、docker-ocamlレポジトリにpushされたら自動的にアップロードする
- 手順書を見ながらAdminやTAがCLIで手動でアップロードする

のどっちかです。10分使ってでもオートにするか、アップロードなんてそんなに頻繁にはしないから手動でやるか、どちらか選んでいただきたいという話でした。

**Comment by ksuenaga** [comment]
なるほど，わかりました．手作業でアップロードするようにすると絶対に忘れてしまって泣きを見ると思うのえ，github actions でやるようにしておいて，main に push されたら　container registry にアップロードされるようにしておきましょう．

**Comment by plveir** [comment]
ではその方針で対応します。
